all:
	gcc -Wall -o server server.c
	gcc -Wall -o server-filename server-filename.c
	gcc -Wall -o server-ack server-ack.c
	gcc -Wall -o server-push server-push.c
	gcc -Wall -o client client.c
	gcc -Wall -o client-filename client-filename.c
	gcc -Wall -o client-ack client-ack.c
	gcc -Wall -o client-push client-push.c
clean:
	rm -f client server recv/*.jpg

